spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
