spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  mail:
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    host: smtp.gmail.com
    port: 587

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
